### ISSUE TITLE
Restructure server_meters data to show relationship between peak and RMS data

### ISSUE THREAD

**Issue by delucis** [delucis/web-gui#2]
Currently `server_meters` is an object containing named arrays of audio level data:

```json
"server_meters": {
  "input_meter_peak_levels": [ ],
  "input_meter_rms_levels": [ ],
  "output_meter_peak_levels": [ ],
  "output_meter_rms_levels": [ ]
}
```

It would be more meaningful to group these as follows:

```json
"server_meters": {
  "input_meter_levels": {
    "peak": [ ],
    "rms": [ ]
  },
  "output_meter_levels": {
    "peak": [ ],
    "rms": [ ]
  }
}
```

Or even:

```json
"server_meters": {
  "input_meter_levels": [
    { 
      "peak": 0.8,
      "rms": 0.48
    },
    { 
      "peak": 0.7,
      "rms": 0.44
    },
  ]
}
```

Such groupings would also facilitate a single meter potentially showing both peak and RMS data, or allowing easy toggling by the user between peak and RMS display.

Would such a restructuring of the server output be feasible?

**Comment by josiah-wolf-oberholtzer** [comment]
Yes, both are feasible.

The PR for implementing the Python-to-JSON functionality is here: https://github.com/josiah-wolf-oberholtzer/supriya/pull/105

Let me know which restructuring you prefer and I can implement it. (Or if you want to practice some Python, you might give it a shot yourself; just open a PR against that PR).

**Comment by josiah-wolf-oberholtzer** [comment]
The method in question is here: https://github.com/josiah-wolf-oberholtzer/supriya/pull/105/files#diff-fe8eb039475965367d9e90f35b2f7b34R146

**Comment by delucis** [comment]
Depends a little on which functionality is most attractive: user toggling; or joint peak & RMS meters. I’d tend towards the latter as it groups data per individual meter, which seems cleanest, and would probably require the least wrangling whatever functionality you wanted.

I’ll have a look at the PR, but I probably have my hands full enough on this end of things. Very close to MVP I think, not accounting for the websockets implementation.

**Comment by josiah-wolf-oberholtzer** [comment]
OK, I'll refactor according to the latter example you provide.

Did you also want the casing of the names changes, e.g. `server-meters` -> `server_meters`?

**Comment by delucis** [comment]
Yes! That’d be great.

**Comment by josiah-wolf-oberholtzer** [comment]
Done in https://github.com/josiah-wolf-oberholtzer/supriya/pull/105/commits/647df4be8143108a143dd9ab6ba420ecac462b94.

**Comment by delucis** [comment]
🎉
